type: "Menu"

entries:
  - label: "Home"
    link: "/"

  - label: "About"
    link: "/#about"

  - label: "Skills"
    link: "/#skills"

  - label: "Works"
    link: "/#works"

  - label: "Contact"
    link: "/#contact"
