type: "Menu"

entries:
  - label: "Home"
    link: "/"

  - label: "About"
    link: "/#about"

  - label: "Skills"
    link: "/#skills"

  - label: "Projects"
    link: "/#project-0"

  - label: "Contact"
    link: "/#contact"

  - label: "Posts"
    link: "/posts"
