type: "Site"

title: "Jane Doe"
description: > 
  Jane Doe is a seasoned Full-Stack Engineer and a recognized authority in the
  realms of Next.js and React development. With an impressive track record of
  delivering high-impact projects and innovative solutions, Jane combines her
  deep technical expertise with a keen eye for user-centric design.

social:
  - label: "Twitter"
    icon: "FaTwitter"
    link: "https://twitter.com/"

  - label: "Facebook"
    icon: "FaFacebook"
    link: "https://facebook.com/"

  - label: "GitHub"
    icon: "FaGithub"
    link: "https://github.com/"

  - label: "LinkedIn"
    icon: "FaLinkedin"
    link: "https://linkedin.com/"
copyright:
  - label: "Copyright © 2023 Iago Bozza. All rights reserved."
  - label: "Next.js Project by Iago Bozza"
    link: "https://github.com/writeonlycode/next-portfolio-splash"
  - label: "Original Design by Akhil T J"
    link: "https://www.figma.com/community/file/1006095821656678611/Developer-Portfolio"
